name: Build and Run Docker for yt-dlp

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: "The video link to download"
        required: true
        type: string

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: docker build -t bola .

      # Step 3: Run the Docker container with yt-dlp
      - name: Run yt-dlp in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/output \
            bola "${{ github.event.inputs.video_link }}"

      # Step 4: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: bola-output
          release_name: Bola Output
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Upload the video to the GitHub Release
      - name: Upload bola.mp4 to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bola.mp4
          asset_name: bola.mp4
          asset_content_type: video/mp4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
